wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717413075.092851
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 7
      - 23
      - 24
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
frame_shift:
  desc: null
  value: 300
hop_length:
  desc: null
  value: null
n_fft:
  desc: null
  value: 50
norm_params_path:
  desc: null
  value: params/norm_params/HUNT4/normalization_params_STFT_feats156_seqlen599/
normalize:
  desc: null
  value: true
padding_val:
  desc: null
  value: 0.0
phase:
  desc: null
  value: false
sequence_length:
  desc: null
  value: 15000
x_columns:
  desc: null
  value:
  - back_x
  - back_y
  - back_z
  - thigh_x
  - thigh_y
  - thigh_z
y_column:
  desc: null
  value: label
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 15
feature_dim:
  desc: null
  value: 500
loss:
  desc: null
  value: MARGIN_LOSS
lr:
  desc: null
  value: 0.001
lr_scheduler:
  desc: null
  value: ExponentialTFDecay
margin:
  desc: null
  value: 5
margin_thresh:
  desc: null
  value: 0.4
mask_fraction:
  desc: null
  value: 0.2
mse_lambda:
  desc: null
  value: 0.01
number_sample:
  desc: null
  value: 1
number_subject:
  desc: null
  value: 2
optimizer:
  desc: null
  value: Adam
temperature:
  desc: null
  value: 0.1
total_subjects:
  desc: null
  value: 22
weight_decay:
  desc: null
  value: 0.0
Algorithm:
  desc: null
  value: FULL MARGIN LOSS
Dataset:
  desc: null
  value: HUNT
Train_DS_size:
  desc: null
  value: 82
Batch_Size:
  desc: null
  value: 16
Epochs:
  desc: null
  value: 15
Patience:
  desc: null
  value: 10
