wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725278511.47469
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 7
      - 23
      - 24
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
frame_shift:
  desc: null
  value: 600
hop_length:
  desc: null
  value: null
n_fft:
  desc: null
  value: 50
norm_params_path:
  desc: null
  value: params/norm_params/HUNT4/normalization_params_STFT_feats156_seqlen599/
normalize:
  desc: null
  value: true
padding_val:
  desc: null
  value: 0.0
phase:
  desc: null
  value: false
sequence_length:
  desc: null
  value: 3000
x_columns:
  desc: null
  value:
  - back_x
  - back_y
  - back_z
  - thigh_x
  - thigh_y
  - thigh_z
y_column:
  desc: null
  value: label
