wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717399848.021129
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 2
      - 7
      - 23
      - 24
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Train Loss
      5: 1
      6:
      - 1
    - 1: Epoch
      5: 1
      6:
      - 1
    - 1: Validation Loss
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/emb\.lin_proj_layer1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.in_proj_weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.in_proj_weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.in_proj_weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.in_proj_bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.in_proj_bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.in_proj_bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.out_proj\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.out_proj\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.out_proj\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.out_proj\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.out_proj\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.self_attn\.out_proj\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.linear2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.0\.norm2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.in_proj_weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.in_proj_weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.in_proj_weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.in_proj_bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.in_proj_bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.in_proj_bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.out_proj\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.out_proj\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.out_proj\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.out_proj\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.out_proj\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.self_attn\.out_proj\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.linear2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.1\.norm2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.in_proj_weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.in_proj_weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.in_proj_weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.in_proj_bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.in_proj_bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.in_proj_bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.out_proj\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.out_proj\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.out_proj\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.out_proj\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.out_proj\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.self_attn\.out_proj\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.linear2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.2\.norm2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.in_proj_weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.in_proj_weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.in_proj_weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.in_proj_bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.in_proj_bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.in_proj_bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.out_proj\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.out_proj\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.out_proj\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.out_proj\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.out_proj\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.self_attn\.out_proj\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.linear2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/transformer_encoder\.layers\.3\.norm2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/emb\.lin_proj_layer\.weight.bins
      5: 1
      6:
      - 1
frame_shift:
  desc: null
  value: 300
hop_length:
  desc: null
  value: null
n_fft:
  desc: null
  value: 50
norm_params_path:
  desc: null
  value: params/norm_params/HUNT4/normalization_params_STFT_feats156_seqlen599/
normalize:
  desc: null
  value: true
padding_val:
  desc: null
  value: 0.0
phase:
  desc: null
  value: false
sequence_length:
  desc: null
  value: 15000
x_columns:
  desc: null
  value:
  - back_x
  - back_y
  - back_z
  - thigh_x
  - thigh_y
  - thigh_z
y_column:
  desc: null
  value: label
batch_size:
  desc: null
  value: 16
dim_prediction_head:
  desc: null
  value: 1028
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 15
feature_dim:
  desc: null
  value: 1028
fine_tune_step:
  desc: null
  value: 0.75
loss:
  desc: null
  value: CrossEntropyLoss
lr:
  desc: null
  value: 1e-4
lr_scheduler:
  desc: null
  value: ExponentialTFDecay
margin:
  desc: null
  value: 0.5
margin_thresh:
  desc: null
  value: 0.4
mask_fraction:
  desc: null
  value: 0.2
metrics:
  desc: null
  value:
  - F1Score
  - Accuracy
  - Precision
  - Recall
mse_lambda:
  desc: null
  value: 0.01
n_prediction_head_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: Adam
output_activation:
  desc: null
  value: softmax
rmv_upstream_layers:
  desc: null
  value: 4
temperature:
  desc: null
  value: 0.1
upstream_algorithm:
  desc: null
  value: TransformerEncoderNetwork
upstream_model_path:
  desc: null
  value: params/selfPAB_upstream/upstream_model.ckpt
weight_decay:
  desc: null
  value: 0.0
weighted_sum_layer:
  desc: null
  value: null
Algorithm:
  desc: null
  value: DownstreamMLP
Dataset:
  desc: null
  value: STFT
Train_DS_size:
  desc: null
  value: 245
Batch_Size:
  desc: null
  value: 16
Epochs:
  desc: null
  value: 15
