wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728497025
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 7
      - 13
      - 17
      - 23
      - 24
      - 37
      - 66
      4: 3.11.5
      5: 0.17.8
      6: 4.32.1
      8:
      - 4
      - 5
      10:
      - 3
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: parameters/encoder_q\.input_fc\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.input_fc\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.input_fc\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.input_fc\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.input_fc\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.input_fc\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv3\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv3\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv3\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv3\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv3\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.conv3\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn3\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn3\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn3\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn3\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn3\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.feature_extractor\.bn3\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.0\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.0\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.0\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.0\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.0\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.0\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.3\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.3\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.3\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.3\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.3\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.3\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.4\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.4\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.4\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.4\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.4\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.4\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.5\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.5\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.5\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.5\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.5\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.5\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.6\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.6\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.6\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.6\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.6\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.6\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.7\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.7\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.7\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.7\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.7\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.tfd\.7\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.sfd\.0\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.sfd\.0\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.sfd\.0\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.sfd\.0\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.sfd\.0\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/encoder_q\.sfd\.0\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.0\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.0\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.0\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.0\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.0\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.0\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/head_q\.2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.0\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.0\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.0\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.0\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.0\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.0\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/head_k\.2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.0\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.0\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.0\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.0\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.0\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/head_q\.0\.weight.bins
      5: 1
      6:
      - 1
    - 1: Epoch
      5: 1
      6:
      - 1
    - 1: Davies-Bouldin Index Features
      5: 1
      6:
      - 1
    - 1: Calinski Harabasz Index Features
      5: 1
      6:
      - 1
    - 1: Silhouette Index Features
      5: 1
      6:
      - 1
    - 1: Joint cluster metrics
      5: 1
      6:
      - 1
class_to_exclude:
  desc: null
  value: 3
hop_length:
  desc: null
  value: 125
n_fft:
  desc: null
  value: 250
num_labels:
  desc: null
  value: 4
seq_length:
  desc: null
  value: 300
win_length:
  desc: null
  value: 250
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 500
feature_dim:
  desc: null
  value: 178
loss:
  desc: null
  value: LS_HATCL_LOSS
lr:
  desc: null
  value: 0.001
lr_scheduler:
  desc: null
  value: ExponentialTFDecay
margin:
  desc: null
  value: 5
margin_thresh:
  desc: null
  value: 0.4
mask_fraction:
  desc: null
  value: 0.3
mloss:
  desc: null
  value: LS_MARGIN_LOSS
mse_lambda:
  desc: null
  value: 0.4
number_sample:
  desc: null
  value: 1
number_subject:
  desc: null
  value: 10
optimizer:
  desc: null
  value: AdamW
out_features:
  desc: null
  value: 32
sequence_sample:
  desc: null
  value: 300
temperature:
  desc: null
  value: 0.5
tnc_window:
  desc: null
  value: 20
total_subjects:
  desc: null
  value: 30000
weight_decay:
  desc: null
  value: 0.0
Algorithm:
  desc: null
  value: CoST
Dataset:
  desc: null
  value: sleepeeg
Train_DS_size:
  desc: null
  value: 989
Batch_Size:
  desc: null
  value: 8
Epochs:
  desc: null
  value: 500
Patience:
  desc: null
  value: 5
Seed:
  desc: null
  value: 42
