wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725302146.458757
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 7
      - 23
      - 24
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
class_to_exclude:
  desc: null
  value: 3
hop_length:
  desc: null
  value: 125
n_fft:
  desc: null
  value: 250
num_labels:
  desc: null
  value: 4
seq_length:
  desc: null
  value: 500
win_length:
  desc: null
  value: 250
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 2
feature_dim:
  desc: null
  value: 252
loss:
  desc: null
  value: LS_HATCL_LOSS
lr:
  desc: null
  value: 0.001
lr_scheduler:
  desc: null
  value: ExponentialTFDecay
margin:
  desc: null
  value: 5
margin_thresh:
  desc: null
  value: 0.4
mask_fraction:
  desc: null
  value: 0.3
mse_lambda:
  desc: null
  value: 0.4
number_sample:
  desc: null
  value: 1
number_subject:
  desc: null
  value: 10
optimizer:
  desc: null
  value: AdamW
out_features:
  desc: null
  value: 32
sequence_sample:
  desc: null
  value: 119
temperature:
  desc: null
  value: 0.5
tnc_window:
  desc: null
  value: 20
total_subjects:
  desc: null
  value: 30000
weight_decay:
  desc: null
  value: 0.0
Algorithm:
  desc: null
  value: VANILLA CONTRASTIVE LOSS
Dataset:
  desc: null
  value: HUNT
Train_DS_size:
  desc: null
  value: 594
Batch_Size:
  desc: null
  value: 8
Epochs:
  desc: null
  value: 2
Patience:
  desc: null
  value: 5
Seed:
  desc: null
  value: 42
